#!/sbin/busybox sh

. /mbs/mbs_const
. /mbs/mbs_funcs.sh

PATH_=$PATH
export PATH=/sbin

LOW_POWER_MODE=`mbs_func_get_low_power_mode`

if [ "$LOW_POWER_MODE" = '1' ]; then
    sh /mbs/init.lpm.sh
    export PATH=$PATH_
    exec /init
fi

# extract block device files
tar xf /misc/dev.tar

#Single or Multi boot mode flag
# this will be changed by kernel build script
BOOT_MODE=0

RECOVERY_MODE=`mbs_func_get_recovery_mode`

if [ "$RECOVERY_MODE" = '1' ]; then
    # recovery mode
    sh /mbs/init.recovery.sh $BOOT_MODE
else
    #normal boot mode
    sh /mbs/init.normal.sh $BOOT_MODE
fi

# cleanup
rm -rf /dev/* /misc/dev.tar

export PATH=$PATH_
exec /init

