#!/sbin/busybox sh

. /mbs/mbs_const

PATH_=$PATH
export PATH=/sbin

mount -t sysfs sysfs /sys
LOW_POWER_MODE=`cat /sys/class/power_supply/battery/batt_lp_charging`
umount /sys

if [ "$LOW_POWER_MODE" = '1' ]; then
  sh /mbs/setup_rom.sh lpm
  export PATH=$PATH_
  exec /init
fi

# extract block device files
tar xf /misc/dev.tar

mount -t proc proc /proc
RECOVERY_MODE=`grep -c bootmode=2 /proc/cmdline`
umount /proc


#foce single boot mode
IS_MODE=1

#check multi mode
if [ "$IS_MODE" = '0' ]; then
  #single boot mode
  mkdir /system
  mkdir /data
  chmod 0771 /data
  RECOVERY_SH=/mbs/init.recovery.sh
  NORMAL_SH=/mbs/init.normal.sh
else
  #mbs mode
  mkdir /xdata
  RECOVERY_SH=/mbs/init.recovery.multi.sh
  NORMAL_SH=/mbs/init.normal.multi.sh

  cp /mbs/swrom /sbin
fi

#check boot mode
if [ "$RECOVERY_MODE" = '1' ]; then
  # recovery mode
  sh $RECOVERY_SH
else
  sh $NORMAL_SH
fi

# cleanup
rm -rf /dev/* /misc/dev.tar

# init start
#mv /_init /init

export PATH=$PATH_
exec /init

